name: Build, test and release container
on:
  push:
    branches:
      - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Lint container file
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: Containerfile
          output-file: hadolint.out
      