name: Build, test and release container
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Lint container file
        id: lint
        continue-on-error: true
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          output-file: hadolint.out
      - name: Output hadolint
        if: failure() && steps.lint.outcome == 'failure'
        run: |
          echo "Hadolint output:" >> "$GITHUB_STEP_SUMMARY"
          echo "$(cat hadolint.out)" >> "$GITHUB_STEP_SUMMARY"
  release:
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Containerfile
          tags: latest
