name: Build, test and release container
on:
  push:
    branches:
      - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Lint container file
        id: lint
        continue-on-error: true
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          output-file: hadolint.out
      - name: Output hadolint
        run: |
          echo 'Hadolint output:\n' >> "$GITHUB_STEP_SUMMARY"
          echo "$(cat hadolint.out)" >> "$GITHUB_STEP_SUMMARY"
